var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,e):$jscomp.polyfillUnisolated(a,b,d,e))};$jscomp.polyfillUnisolated=function(a,b,d,e){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];if(!(f in d))return;d=d[f]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,e){var f=a.split(".");a=1===f.length;e=f[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<f.length-1;g++){var h=f[g];if(!(h in e))return;e=e[h]}f=f[f.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?e[f]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+d+"$"+f),$jscomp.defineProperty(e,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:b})))};
$jscomp.getConstructImplementation=function(){function a(){function d(){}new d;Reflect.construct(d,[],function(){});return new d instanceof d}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(d,e,f){d=b(d,e);f&&Reflect.setPrototypeOf(d,f.prototype);return d}}return function(d,e,f){void 0===f&&(f=d);f=$jscomp.objectCreate(f.prototype||Object.prototype);return Function.prototype.apply.call(d,f,e)||
f}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var d=$jscomp.setPrototypeOf;d(a,b)}else for(d in b)if("prototype"!=d)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d];a.superClass_=b.prototype};$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Reflect.setPrototypeOf",function(a){if(a)return a;if($jscomp.setPrototypeOf){var b=$jscomp.setPrototypeOf;return function(d,e){try{return b(d,e),!0}catch(f){return!1}}}return null},"es6","es5");$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(b,d,e){var f=this.length||0;0>d&&(d=Math.max(0,f+d));if(null==e||e>f)e=f;e=Number(e);0>e&&(e=Math.max(0,f+e));for(d=Number(d||0);d<e;d++)this[d]=b;return this}},"es6","es3");
$jscomp.typedArrayFill=function(a){return a?a:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");var canvas=document.getElementById("canv"),c=canvas.getContext("2d"),width=canvas.width,height=canvas.height,touchX=500,touchY=500;
window.onload=function(){setCanvasScale();startMainMenu()};function startGame(){setCanvasScale();start();update();atMainMenu=!1}window.addEventListener("resize",function(){setCanvasScale()});function start(){}function update(){}function setColor(a){c.fillStyle=a}function fillRect(a,b,d,e){c.fillRect(a*width/1E3,b*height/1E3,d*width/1E3,e*height/1E3)}function fillText(a,b,d,e,f,g){c.font=e*width/1E3+"px "+g;setColor(f);c.fillText(a,b*width/1E3,d*height/1E3)}
function drawImg(a,b,d,e,f){c.drawImage(a,b*width/1E3,d*height/1E3,e*width/1E3,f*height/1E3)}function background(a){c.drawImage(a,0,0,width,height)}function translate(a,b){c.translate(a*width/1E3,b*height/1E3)}function drawLine(a,b,d,e){c.beginPath();c.moveTo(a*width/1E3,b*height/1E3);c.lineTo(d*width/1E3,e*height/1E3);c.stroke();c.closePath()}function moveTo(a,b){c.moveTo(a*width/1E3,b*height/1E3)}function lineTo(a,b){c.lineTo(a*width/1E3,b*height/1E3)}
function setCanvasScale(){width=canvas.width=window.innerWidth;height=canvas.height=window.innerHeight;c.webkitImageSmoothingEnabled=!1;c.mozImageSmoothingEnabled=!1;c.imageSmoothingEnabled=!1}function toRadians(a){return Math.PI/180*a}function random(a,b){return Math.floor(Math.random()*(b-a)+a)}var flashOp=0,flashing=!1;
function flashScreen(a){setColor(a);.3>flashOp&&flashing?flashOp+=.02*deltaTime:(flashing=!1,dead&&(flashOp+=.02*deltaTime));!flashing&&.02<flashOp&&!dead&&(flashOp-=.02*deltaTime);c.globalAlpha=flashOp;fillRect(0,0,1E3,1E3);c.globalAlpha=1}var deltaTime,dlastcalledtime=Date.now();function getDeltaTime(){deltaTime=(Date.now()-dlastcalledtime)/10;dlastcalledtime=Date.now()};var p,enemy,playerSpeed=5,enemySpeed=2;deltaTime=1;var chargers=[],healthDisplay=[],playerHealth=3,dead=!1,rounds=-1,gun,bullets=[],enemyTriangle=[0,0,0,0,0,0,0,0],score=0,chargerImg=new Image,playerImg=new Image,enemyImg=new Image,backgroundImg=new Image,greenHeartImg=new Image,redHeartImg=new Image,titleImg=new Image,gunImg=new Image,song=new Audio,atMainMenu=!0,playButton,quitButton,countdownTime=4,clicked=!1,atDeadMenu=!1;
function startMainMenu(){deltaTime=1;backgroundImg.src="data/textures/Background.png";titleImg.src="data/textures/title.png";playButton=new Button(450,500,100,100,"blue","Play");quitButton=new Button(450,700,100,100,"blue","Quit");updateMainMenu()}
function updateMainMenu(){getDeltaTime();background(backgroundImg);clicked||(drawImg(titleImg,350,100,300,200),playButton.render(),quitButton.render());playButton.clicked()&&!clicked&&(setTimeout(startGame,1500),clicked=!0,countDown());quitButton.clicked()&&window.close();clicked&&fillText(countdownTime,500,500,50,"black","destroyregular");atMainMenu&&setTimeout(updateMainMenu,10)}
function start(){deltaTime=1;atDeadMenu=!1;p=new Player(500,500);enemy=new Enemy(random(50,950),random(50,950));chargerImg.src="data/textures/Charger.png";playerImg.src="data/textures/Player.png";enemyImg.src="data/textures/Enemy.png";backgroundImg.src="data/textures/Background.png";greenHeartImg.src="data/textures/GreenHeart.png";redHeartImg.src="data/textures/RedHeart.png";gunImg.src="data/textures/gun.png";song.src="data/music/song.wav";song.loop=!0;song.volume=.02;score=0;spawnChargers();dead=
!1;for(var a=0;3>a;a++)healthDisplay.push(greenHeartImg);gun=new Gun(500,500);song.play()}
function draw(){background(backgroundImg);c.beginPath();setColor("gray");moveTo(enemyTriangle[0],enemyTriangle[1]);lineTo(enemyTriangle[2],enemyTriangle[3]);lineTo(enemyTriangle[6],enemyTriangle[7]);lineTo(enemyTriangle[4],enemyTriangle[5]);c.fill();c.closePath();p.render(playerImg);enemy.render(enemyImg);for(var a=0;a<chargers.length;a++)chargers[a].render(chargerImg);3<=rounds&&gun.render();for(a=0;a<bullets.length;a++)bullets[a].render();setColor("rgb(50, 50, 50)");fillRect(870,0,140,70);for(a=
1;4>a;a++)drawImg(healthDisplay[a-1],840+40*a,10,30,50);fillText(score,10,60,30,"black","destroyregular");flashScreen("red")}
function update(){getDeltaTime();p.update();p.moveOffScreen();touching&&movePlayer(touchX,touchY);enemy.update();enemySpeed+=3/enemySpeed*.01*deltaTime;enemy.collideWithPlayer()&&enemy.canCollide&&(damagePlayer(),enemy.canCollide=!1);enemy.canCollide||(enemy.collideTimer+=.01*deltaTime,1<=enemy.collideTimer&&(enemy.canCollide=!0,enemy.collideTimer=0));0>=chargers.length&&spawnChargers();3<=rounds&&(gun.update(),mouseDown&&gun.canShoot&&gun.shoot());for(var a=0;a<bullets.length;a++)bullets[a].update(),
.3<bullets[a].time&&bullets.splice(a,1);for(a=0;a<chargers.length;a++)chargers[a].collideWithPlayer()&&(chargers[a].onCollect(),chargers.splice(a,1),score++);draw();enemy.castRays();atDeadMenu||requestAnimationFrame(update)}function movePlayer(a,b){p.x*width/1E3<a&&(p.x+=playerSpeed);p.x*width/1E3>a&&(p.x-=playerSpeed);p.y*height/1E3>b&&(p.y-=playerSpeed);p.y*height/1E3<b&&(p.y+=playerSpeed)}
function spawnChargers(){for(var a=0;10>a;a++){var b=new Charger(random(50,950),random(50,950));chargers.push(b)}rounds++}function deadMenu(){setTimeout(function(){deltaTime=1;atDeadMenu=!0;flashing=!1;playButton=new Button(450,500,100,100,"blue","Play");quitButton=new Button(450,700,100,100,"blue","Quit");updateDeadMenu();clicked=!1;countdownTime=4},1E3)}
function updateDeadMenu(){getDeltaTime();background(backgroundImg);clicked||(fillText("Game Over",300,100,50,"black","destroyregular"),fillText("You survived "+rounds+" rounds.",350,150,15,"black","destroyregular"),fillText("Score: "+score,460,180,10,"black","destroyregular"),playButton.render(),quitButton.render());playButton.clicked()&&!clicked&&(atDeadMenu=!1,flashOp=0,playerSpeed=5,enemySpeed=2,chargers=[],healthDisplay=[],bullets=[],playerHealth=3,rounds=-1,clicked=!0,countDown(),setTimeout(startGame,
1500));clicked&&fillText(countdownTime,500,500,50,"black","destroyregular");quitButton.clicked()&&window.close();dead&&setTimeout(updateDeadMenu,10)}function countDown(){countdownTime--;0<countdownTime&&setTimeout(countDown,500)}function damagePlayer(){playerHealth--;healthDisplay[playerHealth]=redHeartImg;flashing=!0;flashScreen();0>=playerHealth&&(dead=!0,deadMenu())};var Entity=function(a,b,d,e){this.x=a;this.y=b;this.w=d;this.h=e;this.ySpeed=this.xSpeed=0};Entity.prototype.render=function(a){drawImg(a,this.x,this.y,this.w,this.h)};Entity.prototype.update=function(){this.x+=this.xSpeed;this.y+=this.ySpeed};Entity.prototype.collideWithPlayer=function(){if(this.x+this.w>p.x&&this.x<p.x+p.w&&this.y+this.h>p.y&&this.y<p.y+p.h)return!0};var Player=function(a,b){Entity.call(this,a,b,25,50)};$jscomp.inherits(Player,Entity);Player.prototype.moveOffScreen=function(){0>=this.x&&(this.x=0);1E3<=this.x+this.w&&(this.x=1E3-this.w);0>=this.y&&(this.y=0);1E3<=this.y+this.h&&(this.y=1E3-this.h)};var Enemy=function(a,b){Entity.call(this,a,b,25,50);this.dir=5;this.moving=!1;this.fov=90;this.canCollide=!0;this.collideTimer=0;this.canShoot=!1;this.gunTimer=0;this.turnDirection=1;this.hitPlayer=!1};$jscomp.inherits(Enemy,Entity);
Enemy.prototype.update=function(){this.moving&&(this.x<p.x&&(this.x+=enemySpeed),this.x>p.x&&(this.x-=enemySpeed),this.y>p.y&&(this.y-=enemySpeed),this.y<p.y&&(this.y+=enemySpeed));if(3<=rounds&&(this.canShoot||(this.gunTimer+=.01*deltaTime,2<this.gunTimer&&(this.canShoot=!0,this.gunTimer=0)),this.canShoot&&this.moving)){var a=new Bullet(this.x,this.y,Math.atan2(-(this.y-p.y),-(this.x-p.x)),"enemy");bullets.push(a);this.canShoot=!1}};
Enemy.prototype.castRay=function(a,b,d,e){for(var f=a+Math.cos(d),g=b+Math.sin(d),h=!1,k=0;!h;)k+=.1,f=a+Math.cos(d)*k,g=b+Math.sin(d)*k,this.moving||(this.dir+=5E-8*enemySpeed*deltaTime*this.turnDirection),1E3<k&&(h=!0),f>p.x&&f<p.x+p.w&&g>p.y&&g<p.y+p.h&&(h=!0,e==-(this.fov/2)&&(this.turnDirection=-1),e==(this.fov-10)/2&&(this.turnDirection=1),this.moving=!0);dead||(e==-(this.fov/2)&&(enemyTriangle[0]=a,enemyTriangle[1]=b,enemyTriangle[2]=f+1E3*Math.cos(d),enemyTriangle[3]=g+1E3*Math.sin(d)),e==
(this.fov-10)/2&&(enemyTriangle[4]=a,enemyTriangle[5]=b,enemyTriangle[6]=f+1E3*Math.cos(d),enemyTriangle[7]=g+1E3*Math.sin(d)))};Enemy.prototype.castRays=function(){this.moving=this.hitPlayer=!1;for(var a=-(this.fov/2);a<this.fov/2;a+=5){var b=this.dir+toRadians(a);this.castRay(this.x+this.w/2,this.y+this.h/2,b,a)}};var Charger=function(a,b){Entity.call(this,a,b,20,30)};$jscomp.inherits(Charger,Entity);Charger.prototype.onCollect=function(){1<=enemySpeed&&enemySpeed--};var Bullet=function(a,b,d,e){Entity.call(this,a,b,2,5);this.xSpeed=random(15,18);this.ySpeed=random(15,18);this.dir=d;this.time=0;this.shootSFX=new Audio("data/sfx/shoot.wav");this.start=e;this.shootSFX.volume=.1;this.shootSFX.play();this.used=!1};$jscomp.inherits(Bullet,Entity);Bullet.prototype.render=function(){setColor("yellow");fillRect(this.x,this.y,this.w,this.h)};
Bullet.prototype.update=function(){this.x+=this.xSpeed*deltaTime*Math.cos(this.dir);this.y+=this.ySpeed*deltaTime*Math.sin(this.dir);.3>this.time&&"player"==this.start&&(this.time+=.01*deltaTime,p.x-=this.time/2*deltaTime*this.xSpeed*Math.cos(this.dir),p.y-=this.time/2*deltaTime*this.ySpeed*Math.sin(this.dir));"player"==this.start&&this.x+this.w>enemy.x&&this.x<enemy.x+enemy.w&&this.y+this.h>enemy.y&&this.y<enemy.y+enemy.h&&.3>this.time&&(this.time+=.01*deltaTime,enemy.x+=this.time/2*deltaTime*this.xSpeed*
10*Math.cos(this.dir),enemy.y+=this.time/2*deltaTime*this.ySpeed*10*Math.sin(this.dir),this.used||(score++,this.used=!0));"player"!=this.start&&this.x+this.w>p.x&&this.x<p.x+p.w&&this.y+this.h>p.y&&this.y<p.y+p.h&&!this.used&&(damagePlayer(),this.used=!0)};var Gun=function(a,b){this.x=a;this.y=b;this.dir=0;this.canShoot=!0;this.shootTimer=0};Gun.prototype.render=function(){c.save();translate(this.x,this.y);c.rotate(this.dir);drawImg(gunImg,-20,-20,40,40);c.restore()};
Gun.prototype.update=function(){this.x=p.x+p.w/2;this.y=p.y+p.h/2;this.dir=Math.atan2(mouseY-p.y*height/1E3,mouseX-p.x*width/1E3);touching&&(this.dir=Math.atan2(touchY-p.y*height/1E3,touchX-p.x*width/1E3));this.canShoot||(1<this.shootTimer?(this.canShoot=!0,this.shootTimer=0):this.shootTimer+=.01*deltaTime)};Gun.prototype.shoot=function(){this.canShoot=!1;for(var a=0;5>a;a++){var b=new Bullet(p.x,p.y,this.dir,"player");bullets.push(b)}};function keyDown(a){switch(a.keyCode){case 68:p.xSpeed=playerSpeed;break;case 65:p.xSpeed=-playerSpeed;break;case 83:p.ySpeed=playerSpeed;break;case 87:p.ySpeed=-playerSpeed}}function keyUp(a){switch(a.keyCode){case 68:case 65:p.xSpeed=0;break;case 83:case 87:p.ySpeed=0}}document.onkeydown=keyDown;document.onkeyup=keyUp;var mouseX,mouseY,mouseDown=!1;window.addEventListener("mousedown",function(a){mouseDown=!0;mouseX=a.clientX;mouseY=a.clientY});
window.addEventListener("mousemove",function(a){mouseX=a.clientX;mouseY=a.clientY});window.addEventListener("mouseup",function(){mouseDown=!1});var touching=!1;function getTouchPosition(a){touchX=a.touches[0].clientX;touchY=a.touches[0].clientY}window.addEventListener("touchstart",function(a){touching=!0;!atMainMenu&&!dead&&3<=rounds&&gun.canShoot&&gun.shoot();getTouchPosition(a)});window.addEventListener("touchmove",function(a){getTouchPosition(a)});
window.addEventListener("touchend",function(){touching=!1});var Button=function(a,b,d,e,f,g){this.x=a;this.y=b;this.w=d;this.h=e;this.text=g;this.color=f};Button.prototype.render=function(){setColor(this.color);fillRect(this.x,this.y,this.w,this.h);fillText(this.text,this.x+this.w/10,this.y+this.h/1.3,40,"white","Arial")};
Button.prototype.clicked=function(){if(touchX>this.x*width/1E3&&touchX<this.x*width/1E3+this.w*width/1E3&&touchY>this.y*height/1E3&&touchY<this.y*height/1E3+this.h*height/1E3||mouseX>this.x*width/1E3&&mouseX<this.x*width/1E3+this.w*width/1E3&&mouseY>this.y*height/1E3&&mouseY<this.y*height/1E3+this.h*height/1E3&&mouseDown)return!0};
